---
apiVersion: "v2"
name: "yopass"
description: "A lightweight Helm chart for Yopass that prioritizes transparency and flexibility"
type: "application"
icon: "https://repository-images.githubusercontent.com/16027367/5e148d00-d9f9-11e9-8fa7-04b02283d9af"
keywords:
  - "yopass"
  - "secrets"
  - "security"
maintainers:
  - name: "ernail"
    email: "nagel.eric.95@googlemail.com"
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/erNail/yopass-chart
    - name: support
      url: https://github.com/erNail/yopass-chart/issues
version: "0.0.0"
# renovate: image=jhaals/yopass
appVersion: "12.4.0"
